# @package _global_

paths:
  subset_root: /SSD/datasets/cstims_laion_natural_subset
  preprocessed_dirs:
    raw: /SSD/datasets/cstims_laion_natural_subset_memmaps
    fitted: /SSD/datasets/cstims_laion_natural_subset_memmaps_encoded
  model_list_csv: /home/jroth/rsa_based_selection/data/resources/model_list.csv
  output_base: /home/jroth/rsa_based_selection/outputs/select_controversial_stimuli
  encoding_root: /home/jroth/rsa_based_selection/experiments/encoding_fitting/results/encoding_20251222_141301
  classifier_path: /home/jroth/rsa_based_selection/data/resources/laion_natural_img_clf.pkl