# @package _global_

paths:
  subset_root: /SSD/datasets/cstims_laion_natural_subset
  preprocessed_dirs:
    raw: /SSD/datasets/cstims_laion_natural_subset_memmaps
    fitted: /SSD/datasets/cstims_laion_natural_subset_memmaps_encoded
  model_list_csv: /home/jroth/cstims/00_stimulus_selection/resources/model_list.csv
  output_base: /home/jroth/cstims/00_stimulus_selection/results/selected_stimuli
  encoding_root: /home/jroth/cstims/01_brain_model_alignment/results/encoding_models/encoding_20251222_141301
  classifier_path: /home/jroth/cstims/00_stimulus_selection/resources/laion_natural_img_clf.pkl
