# @package _global_

paths:
  model_list_csv: /u/rothj/cstims/data/resources/model_list.csv
  cache_root: /ptmp/rothj/deepvision_fmri/cache
  deepvision_root: /ptmp/rothj/deepvision_fmri
  output_root: /u/rothj/cstims/outputs/deepvision_encoding_models_refitted
