# @package _global_

paths:
  model_list_csv: /u/rothj/cstims/00_stimulus_selection/resources/model_list.csv
  cache_root: /ptmp/rothj/deepvision_fmri/cache
  deepvision_root: /ptmp/rothj/deepvision_fmri
  output_root: /u/rothj/cstims/01_brain_model_alignment/results/encoding_models/deepvision_encoding_models_refitted
