# @package _global_

method_name: multi_view

tracks:
  - name: raw
    type: identity
  - name: fitted
    type: encoding
    encoding_name: sub-01_hlvis

track_aggregation:
  norm_method: zscore
  agg_method: mean
